import { Settings } from "./Settings";

// Maps a setting to the property on the Settings class
export const settingsMap = new Map<string, keyof Settings>([
  ["NAB.SignToolPath", "signToolPath"],
  ["NAB.SigningCertificateName", "signingCertificateName"],
  ["NAB.SigningTimeStampServer", "signingTimeStampServer"],
  ["NAB.ShowXlfHighlights", "showXlfHighlights"],
  ["NAB.XlfHighlightsDecoration", "xlfHighlightsDecoration"],
  ["NAB.UseExternalTranslationTool", "useExternalTranslationTool"],
  ["NAB.SetExactMatchToState", "setExactMatchToState"],
  ["NAB.ClearTargetWhenSourceHasChanged", "clearTargetWhenSourceHasChanged"],
  ["NAB.DetectInvalidTargets", "detectInvalidTargets"],
  ["NAB.UseDTS", "useDTS"],
  ["NAB.DTS ProjectId", "dtsProjectId"],
  ["NAB.Exact Match To State", "setDtsExactMatchToState"],
  ["NAB.SearchReplaceBeforeSaveXliff", "searchReplaceBeforeSaveXliff"],
  ["NAB.LanguageCodesInComments", "languageCodesInComments"],
  ["NAB.CopilotChatPrompts", "copilotChatPrompts"],
  ["NAB.ReplaceSelfClosingXlfTags", "replaceSelfClosingXlfTags"],
  ["NAB.SearchOnlyXlfFiles", "searchOnlyXlfFiles"],
  ["NAB.MatchTranslation", "matchTranslation"],
  ["NAB.MatchBaseAppTranslation", "matchBaseAppTranslation"],
  ["NAB.AutoAcceptSuggestions", "autoAcceptSuggestions"],
  ["NAB.TranslationSuggestionPaths", "translationSuggestionPaths"],
  ["NAB.ConsoleLogOutput", "consoleLogOutput"],
  ["NAB.LoadSymbols", "loadSymbols"],
  [
    "NAB.TooltipDocsIgnorePageExtensionIds",
    "tooltipDocsIgnorePageExtensionIds",
  ],
  ["NAB.TooltipDocsIgnorePageIds", "tooltipDocsIgnorePageIds"],
  ["NAB.TooltipDocsFilePath", "tooltipDocsFilePath"],
  [
    "NAB.GenerateTooltipDocsWithExternalDocs",
    "generateTooltipDocsWithExternalDocs",
  ],
  [
    "NAB.GenerateDeprecatedFeaturesPageWithExternalDocs",
    "generateDeprecatedFeaturesPageWithExternalDocs",
  ],
  [
    "NAB.IgnoreTransUnitInGeneratedDocumentation",
    "ignoreTransUnitInGeneratedDocumentation",
  ],
  ["NAB.DocsRootPath", "docsRootPath"],
  ["NAB.RemoveObjectNamePrefixFromDocs", "removeObjectNamePrefixFromDocs"],
  ["NAB.DocsIgnorePaths", "docsIgnorePaths"],
  ["NAB.CreateTocFilesForDocs", "createTocFilesForDocs"],
  ["NAB.documentation.output.indexFile", "documentationOutputIndexFile"],
  [
    "NAB.documentation.output.indexFilePath",
    "documentationOutputIndexFilePath",
  ],
  [
    "NAB.documentation.output.indexFileDepth",
    "documentationOutputIndexFileDepth",
  ],
  ["NAB.documentation.api.IncludeDataType", "documentationAPIIncludeDataType"],
  ["NAB.documentation.yamlTitle.enabled", "documentationYamlTitleEnabled"],
  ["NAB.documentation.yamlTitle.prefix", "documentationYamlTitlePrefix"],
  ["NAB.documentation.yamlTitle.suffix", "documentationYamlTitleSuffix"],
  ["NAB.IncludeTablesAndFieldsInDocs", "includeTablesAndFieldsInDocs"],
  ["NAB.CreateInfoFileForDocs", "createInfoFileForDocs"],
  ["NAB.CreateUidForDocs", "createUidForDocs"],
  ["NAB.Xliff CSV Export Path", "xliffCSVExportPath"],
  ["NAB.CSV Import Target State", "xliffCSVImportTargetState"],
  [
    "NAB.RefreshXlfAfterFindNextUntranslated",
    "refreshXlfAfterFindNextUntranslated",
  ],
  ["NAB.EnableTranslationsOnHover", "enableTranslationsOnHover"],
  ["NAB.EnableTelemetry", "enableTelemetry"],
  ["NAB.EnableTroubleshootingCommands", "enableTroubleshootingCommands"],
  ["NAB.EnableXliffCache", "enableXliffCache"],
  ["NAB.PreferLockedTranslations", "preferLockedTranslations"],
  ["NAB.TranslationFilenamePattern", "translationFilenamePattern"],

  // Other extension's settings:
  ["al.packageCachePath", "packageCachePath"],
]);
