# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test Coverage

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        node-version: [14.x]
    runs-on: ubuntu-latest
    env:
      working-directory: ./extension/
      NAB_DISABLE_TELEMETRY: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
        working-directory: ${{env.working-directory}}
      - name: Code Coverage
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run test:coverage
          working-directory: ${{env.working-directory}}
      - name: Check Code Coverage
        run:  npx nyc report --reporter=lcov --reporter=text-summary --check-coverage
        working-directory: ${{env.working-directory}}
      # - name: Tar files
      #   run: tar -cvf my_files.tar ./coverage/**
      #   working-directory: ${{env.working-directory}}
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: ${{env.working-directory}}coverage/**
          retention-days: 7
