name: Publish To Marketplace
on: 
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Release type'
        required: true
        type: choice
        default: 'pre-release'
        options:
          - pre-release
          - release-patch
          - release
jobs:
    release:
      runs-on: ubuntu-latest
      env:
        working-directory: ./extension/
        RELEASETYPE: ${{ github.event.inputs.releaseType }}
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: 16.x

        - name: Git config
          run: |
            git config user.name "github-actions"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config advice.addIgnoredFile false

        - name: Install dependencies
          run: |
             npm ci
             npm install -g vsce
          working-directory: ${{env.working-directory}}

        - name: "Create ${{ env.RELEASETYPE }}"
          run: |
            pwd
            ../dev-tools/PowerShell/library/Publish-ToMarketPlace-Workflow.ps1 -releaseType ${{ env.RELEASETYPE }}
          shell: pwsh
          working-directory: ${{env.working-directory}}

        - name: Upload artifacts
          uses: actions/upload-artifact@v2
          with:
            path: ./extension/*.vsix
            retention-days: 7

        # If the run failed, npm log may help to diagnose.
        - name: "(debug) Upload npm log"
          if: ${{ !success() }}
          uses: actions/upload-artifact@v2
          with:
            name: "npm-debug-log"
            path: "~/.npm/_logs"
