name: Publish To Marketplace
on: 
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Release type'
        required: true
        type: choice
        default: 'pre-release'
        options:
          - pre-release
          - release
      updatedChangelog:
        description: 'Reminder to Update CHANGELOG! (Not done by this workflow)'
        type: boolean
        required: true
jobs:
    release:
      runs-on: windows-latest
      env:
        working-directory: ./extension/
        RELEASETYPE: ${{ github.event.inputs.releaseType }}
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: 16.x

        - name: Git config
          run: |
            git config user.name "github-actions"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config advice.addIgnoredFile false

        - name: Install dependencies
          run: |
             npm ci
             npm install -g vsce
          working-directory: ${{env.working-directory}}

        - name: "Package: ${{ env.RELEASETYPE }}"
          id: packageVSIX
          run: |
            ../dev-tools/PowerShell/library/Publish-ToMarketPlace-Workflow.ps1 -releaseType ${{ env.RELEASETYPE }}
          shell: pwsh
          working-directory: ${{env.working-directory}}

        - name: Upload artifacts
          uses: actions/upload-artifact@v2
          with:
            name: vsix
            path: ./extension/*.vsix
            retention-days: 7

        - name: Publish ${{env.RELEASETYPE }} to Visual Studio Marketplace
          uses: HaaLeo/publish-vscode-extension@v1
          with:
            preRelease: ${{env.RELEASETYPE == 'pre-release'}}
            pat: ${{ secrets.VSCE_PAT }}
            registryUrl: https://marketplace.visualstudio.com
            extensionFile: ${{ steps.packageVSIX.outputs.vsixPath }}
            working-directory: ${{env.working-directory}}

        - name: Push Commits
          run: |
            git push
            git push --tags

        # If the run failed, npm log may help to diagnose.
        - name: "(debug) Upload npm log"
          if: ${{ !success() }}
          uses: actions/upload-artifact@v2
          with:
            name: "npm-debug-log"
            path: "~/.npm/_logs"
